## DATA SCIENCE PRACTICE

In [9]:
import mysql.connector
import pandas as pd 
import requests
from bs4 import BeautifulSoup

In [17]:
try:
    connection= mysql.connector.connect(
    host="database-comp3162.cqb8o27401uq.us-east-2.rds.amazonaws.com",
    port= 3306,
    user='comp3162user',
    password='Password876',
    database='comp3162'
    )
    print("Connection Succesful")

    #Execute SQL query
    cursor=connection.cursor()
    cursor.execute("SELECT * FROM Patients")
    rows= cursor.fetchall()
    for row in rows:
        print(row)

    # Close cursor and connection
    
    cursor.close()
    connection.close()

except mysql.connector.Error as error:
    print("Connection Error", error)

Connection Succesful
(1, 45, 'Male', 25.6, 120, 190, 'Normal', 'Yes', 'Positive')
(2, 55, 'Female', 29.8, 140, 220, 'High', 'No', 'Negative')
(3, 60, 'Male', 27.3, 130, 210, 'Normal', 'Yes', 'Positive')
(4, 35, 'Female', 22.5, 110, 180, 'Normal', 'No', 'Negative')
(5, 50, 'Male', 31.1, 150, 240, 'High', 'Yes', 'Positive')
(6, 65, 'Male', 26.5, 125, 200, 'High', 'Yes', 'Positive')
(7, 40, 'Female', 24.9, 115, 170, 'Normal', 'No', 'Negative')
(8, 70, 'Male', 27.9, 135, 230, 'High', 'Yes', 'Positive')
(9, 58, 'Female', None, 130, 210, 'Normal', 'Yes', 'Positive')
(10, 45, 'Male', 28.3, None, 220, 'High', 'No', 'Negative')
(11, 53, 'Female', 26.8, 125, None, 'Normal', 'No', 'Negative')
(12, 62, 'Male', 30.5, 145, 240, None, 'Yes', 'Positive')
(13, 47, 'Male', 25.1, 122, 195, 'Normal', 'Yes', 'Positive')
(14, 57, 'Female', 27.4, 138, 215, 'Normal', 'No', 'Negative')
(15, 64, 'Male', 28.6, 132, 225, 'High', 'Yes', 'Positive')
(16, 38, 'Female', 23.8, 114, 175, 'Normal', 'No', 'Negative')
(17, 48, 'Male', 30.2, 148, 230, 'High', 'Yes', 'Positive')
(18, 69, 'Male', 26.2, 128, 205, 'Normal', 'Yes', 'Positive')
(19, 42, 'Female', 29.7, 142, 218, 'High', 'No', 'Negative')
(20, 56, 'Male', 24.5, 123, 198, 'Normal', 'Yes', 'Positive')
(21, 61, 'Female', 27.9, 136, 227, 'Normal', 'No', 'Negative')
(22, 36, 'Male', 25.9, 126, 202, 'High', 'Yes', 'Positive')
(23, 52, 'Male', 22.3, 108, 178, 'Normal', 'No', 'Negative')
(24, 63, 'Female', 30.4, 144, 235, 'High', 'Yes', 'Positive')
(25, 41, 'Male', 27.1, 134, 215, 'Normal', 'Yes', 'Positive')
(26, 59, 'Female', 26.6, 130, 212, 'Normal', 'No', 'Negative')
(27, 68, 'Male', 28.9, 139, 222, 'High', 'Yes', 'Positive')
(28, 37, 'Male', 24.2, 120, 192, 'Normal', 'Yes', 'Positive')
(29, 49, 'Female', 29.5, 141, 217, 'High', 'No', 'Negative')
(30, 54, 'Male', 25.8, 124, 200, 'Normal', 'Yes', 'Positive')
(31, 66, 'Female', 28.2, 137, 224, 'Normal', 'No', 'Negative')
(32, 39, 'Male', 27.6, 133, 210, 'High', 'Yes', 'Positive')
(33, 51, 'Male', 23.7, 109, 180, 'Normal', 'No', 'Negative')
(34, 70, 'Female', 30.1, 147, 231, 'High', 'Yes', 'Positive')
(35, 43, 'Male', 26.4, 129, 208, 'Normal', 'Yes', 'Positive')
(36, 58, 'Female', 29.3, 140, 216, 'High', 'No', 'Negative')
(37, 67, 'Male', 26.7, 131, 214, 'Normal', 'Yes', 'Positive')
(38, 44, 'Male', 25.7, 121, 196, 'Normal', 'Yes', 'Positive')
(39, 60, 'Female', 28.7, 135, 226, 'Normal', 'No', 'Negative')
(40, 50, 'Male', 24.4, 125, 198, 'High', 'Yes', 'Positive')
(41, 65, 'Female', 27.8, 138, 220, 'High', 'No', 'Negative')
(42, 35, 'Male', 26.1, 127, 204, 'Normal', 'Yes', 'Positive')
(43, 55, 'Male', 22.8, 111, 182, 'Normal', 'No', 'Negative')
(44, 63, 'Female', 30.6, 146, 236, 'High', 'Yes', 'Positive')
(45, 40, 'Male', 27.4, 132, 216, 'Normal', 'Yes', 'Positive')
(46, 57, 'Female', 26.9, 131, 213, 'Normal', 'No', 'Negative')
(47, 66, 'Male', 28.1, 136, 223, 'High', 'Yes', 'Positive')
(48, 38, 'Male', 24.3, 119, 194, 'Normal', 'Yes', 'Positive')
(49, 52, 'Female', 29.6, 143, 219, 'High', 'No', 'Negative')
(50, 68, 'Male', 25.5, 124, 199, 'Normal', 'Yes', 'Positive')

In [23]:
# Exporting data to a csv file
df=pd.DataFrame(rows, columns=['PatientID','Age','Sex','BMI','BloodPressure','Cholesterol','BloodSugar','FamilyHistory','CancerStatus'])
values={'BMI':40.2,'BloodPressure':160, 'Cholesterol':250.0, 'BloodSugar':'High'}
df= df.fillna(value=values)
df.to_csv('Patients.csv',index=False)

In [24]:
#Importing data from csv file
df=pd.read_csv('Patients.csv')
df.head()

,PatientID,Age,Sex,BMI,BloodPressure,Cholesterol,BloodSugar,FamilyHistory,CancerStatus
0,1,45,Male,25.6,120.0,190.0,Normal,Yes,Positive
1,2,55,Female,29.8,140.0,220.0,High,No,Negative
2,3,60,Male,27.3,130.0,210.0,Normal,Yes,Positive
3,4,35,Female,22.5,110.0,180.0,Normal,No,Negative
4,5,50,Male,31.1,150.0,240.0,High,Yes,Positive

In [25]:
# Check for null values in data
df.isnull()

,PatientID,Age,Sex,BMI,BloodPressure,Cholesterol,BloodSugar,FamilyHistory,CancerStatus
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False

## PYTHON REQUEST LIBRARY

In [32]:
#  using the python request library 
import json
url="http://universities.hipolabs.com/search?country=India"
response=requests.get(url) # Use the request library to get the contents from the url
Data=[]

for i in range(0,433): ## Iterate through the JSON for selected keys
    json_data= json.loads(response.text)
    name=json_data[i]['name']
    State= json_data[i]['state-province']
    Data.append([name,State])

In [29]:
# Inserting data into a dataframe
df=pd.DataFrame(Data,columns=['Name','State'])
# Converting dataframe to csv file
df.to_csv('Data.csv', index=False)

## PYTHON AND BEATIFUL SOUP

In [30]:
# Scraping the contents of a webpage using request and beautifulsoup library
books=[]
# Iterating through contents of webapge, for multiple pages
for i in range(1,3):
    url= f"https://books.toscrape.com/catalogue/category/books/mystery_3/page-{i}.html"
    response= requests.get(url)
    response= response.content
    # Parsing the contents of the webpages
    soup= BeautifulSoup(response,"html.parser")
    ol= soup.find('ol')
    articles= ol.find_all('article',class_='product_pod')
    
    # Selecting specific contents of webpage
    for article in articles:
        image=article.find('img')
        title=image.attrs['alt']
        rating= article.find('p')
        rating= rating['class'][1]
        price=article.find('p',class_='price_color').text
        price=float(price[1:])
        books.append([title,price,rating])

In [31]:
# Inserting data into a dataframe 
df= pd.DataFrame(books,columns=['Title','Price','Rating'])
# Coverting dataframe to a csv file
df.to_csv('books.csv',index=False)